---
title: "Works"
author: "Takuya Kubo"
date: "1/23/2022"
output:
    html_document:
        css: "./content/works.css" 
---

## 1. 論文
+ 久保琢也, 平井克之 (2021)「研究IRにおける科研費分析の効率化を目指したWebアプリケーションの開発」『大学評価とIR』13, 3-12.
+ 久保琢也, 伊藤広幸 (2021)「J-STAGEを活用した日本の学術論文データの整備」『大学評価とIR』12, 26-35.
+ 平井克之, 岡崎麻紀子, 奥津佐恵子, 久保琢也, 矢吹命大, 渡邉優香 (2021)「研究力分析の効率化・高度化に関する Code for Research Administration の取組み:URAによる機関を越えた連携」『情報の科学と技術』
+ 久保琢也 (2020)「大学図書館における人文社会系の専門書の所蔵状況 ―CiNii BooksとopenBDを用いた予備的調査―」 『第９回大学情報・機関調査研究集会 論文集』
+ 久保琢也, 伊藤広幸 (2020)「基盤研究 (A) にステップアップした研究者の科研費採択履歴の特徴」『大学評価とIR』11, 15-24.
+ 久保琢也 (2016)『OS語順の産出における普遍性と言語個別性 : カクチケル語VOS語順における検討』広島大学学位論文
+ 久保琢也, 小野創, 田中幹大, 小泉政利,  酒井弘 (2015) 「カクチケル語VOS語順の産出メカニズム−有生性の効果を通して−」『認知科学』22(4), 591-603.
+ 久保琢也 (2014)「カクチケル語における語順の選択に影響を与える要因−談話的卓立性を手がかりとして−」 『広島大学教育学研究科紀要』2(63)
+ 久保琢也 (2013)「名詞句の類似性が語順の選択に与える影響−カクチケル語における検討−」『電子情報通信学会技 術研究報告』113, 63-68.  
+ 久保琢也 (2011)「VOS言語において有生性が語順に与える影響−カクチケル語における線画描写課題での検討−」『電子情報通信学会技 術研究報告』111, 19-24. 


---

## 2. 発表  
+ 久保琢也, Hansen Marc, 平井克之, 間宮るい (2021)「機関を超えたURAによる産学連携等実施状況を分析するためのWebアプリケーションの開発」 第７回リサーチアドミニストレーター協議会 年次大会  
+ 伊藤広幸, 久保琢也 (2021)「多様な強みを把握するための研究力分析-AMEDfindとJ-STAGEを用いた試行」第７回リサーチアドミニストレーター協議会 年次大会
+ 久保琢也, 伊藤広幸 (2021)「J-STAGEを活用した日本の学術論文データの整備」大学評価コンソーシアム 継続的改善のためのIR/IEセミナー「R1 IR実務担当者セッション」
+ 久保琢也, Hansen Marc, 平井克之, 間宮るい (2021)「日本の大学の研究活動を分析するためのWebアプリケーションの開発−機関を越えた共同開発プロジェクト−」第10回超異分野学会
+ 久保琢也 (2020)「大学図書館における人文社会系の専門書の所蔵状況―CiNii BooksとopenBDを用いた予備的調査―」第９回大学情報・機関調査研究集会
+ 久保琢也 (2020)「R言語を用いたオンライン科研費分析ツールの開発−研究力分析業務の効率化・高度化・民主化に向けて−」第６回リサーチ・アドミニストレーター協議会 年次大会
+ 久保琢也, 伊藤広幸 (2019)「信州大学の研究IR推進体制と調査分析事例」第３回研究大学コンソーシアムシンポジウム
+ 田中久美子, 高橋仁, 久保琢也 (2019)「科研費を基にした外部資金獲得につながるURA支援の在り方についての考察」第５回リサーチ・アドミニストレーター協議会 年次大会
+ 久保琢也, 伊藤広幸 (2019)「科研費ステップアップを後押しする科研費分析を目指して-基盤研究(A)採択者の科研費採択履歴調査とその活用-」第５回リサーチ・アドミニストレーター協議会 年次大会
+ 久保琢也 (2017)「人文社会系学術雑誌リストの作成に挑む」第3回人文・社会科学系研究推進フォーラム  
+ Kubo, T., Ono, H., Tanaka, M., Koizumi, M., Sakai, H. (2013) Effects of similarity in the Production of VOS word order in Kaqchikel. Architecture and Mechanisms of Language Processing (AMLaP)
+ Kubo, T., Ono, H., Tanaka, M., Koizumi, M., Sakai, H. (2012) How does animacy affect word order in a VOS language. Annual CUNY Conference on Human Sentence Processing

---


## ３. 受賞  
+ 第７回年次大会個人発表賞「多様な強みを把握するための研究力分析-AMEDfindとJ-STAGEを用いた試行」リサーチ・アドミニストレーター協議会, 2021年9月
+ 第７回年次大会個人発表賞「機関を超えたURAによる産学連携等実施状況を分析するためのWebアプリケーションの開発」リサーチ・アドミニストレーター協議会, 2021年9月
+ 第６回年次大会個人発表賞「R言語を用いたオンライン科研費分析ツールの開発− 研究力分析業務の効率化・高度化・民主化に向けて−」リサーチ・アドミニストレーター協議会, 2020年9月
+ 第５回年次大会ポスター発表賞「科研費ステップアップを後押しする科研費分析を目指して- 基盤研究 (A) 採択者の科研費採択履歴調査とその活用 -」 リサーチ・アドミニストレーター協議会, 2019年9月

---

## ４. 外部資金  
+ 日本学術振興会 科学研究費助成事業 若手研究「人文社会系の専門書の出版数及び図書館における所蔵状況に関する包括的研究」2021年4月 - 2024年3月（代表）
+ 第49回リバネス研究費 日本の研究.com賞「研究力調査分析業務の効率化・高度化・民主化に向けたオンライン分析ツールの開発」2020年10月 -（代表）
+ 日本学術振興会 科学研究費助成事業 特別研究員奨励費「言語類型論的差異と文産出モデルの普遍性ーＯＳ言語における検討ー」2013年4月 - 2015年3月 （代表）

---

